services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://root:root@postgres:5432/blocktweet_db
      - NODE_ENV=production
    networks:
      - app_network
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blocktweet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      NODE_ENV: production
    networks:
      - app_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --webroot --webroot-path=/data/letsencrypt
      --email gallonemilien@gmail.com --agree-tos --no-eff-email
      --keep-until-expiring
      -d panneauramix.fr
      -d www.panneauramix.fr
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - ./nginx:/var/www/html
    networks:
      - app_network


networks:
  app_network:
    driver: bridge