version: '3.8'

services:
  api:
    container_name: td7-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB=td7
    ports:
      - "3000:80"
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: td7-mongo
    image: mongo:8.0
    environment:
      - MONGO_INITDB_DATABASE=td7
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.4-alpine
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  front:
    container_name: td7-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"

  reverse-proxy:
    container_name: td7-reverse-proxy
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
      - front

volumes:
  mongodb_data:
  redis-data: