# renew_before_expiry = 30 days
version = 3.0.1
archive_dir = /etc/letsencrypt/archive/panneauramix.fr
cert = /etc/letsencrypt/live/panneauramix.fr/cert.pem
privkey = /etc/letsencrypt/live/panneauramix.fr/privkey.pem
chain = /etc/letsencrypt/live/panneauramix.fr/chain.pem
fullchain = /etc/letsencrypt/live/panneauramix.fr/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 3c79e2cee2c3cf4e9ddee485a1e44016
authenticator = webroot
webroot_path = /data/letsencrypt,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
panneauramix.fr = /data/letsencrypt
www.panneauramix.fr = /data/letsencrypt
